script_template: inno_setup.iss
app_id: 728B3532-C74B-4870-9068-BE70FE12A3E6
<<<<<<< HEAD
app_name: FlClash
publisher: chen08209
publisher_url: https://github.com/chen08209/FlClash
display_name: FlClash
=======
app_name: honngshu
publisher: chen08209
publisher_url: https://github.com/chen08209/FlClash
display_name: honngshu
>>>>>>> parent of a1b7d14 (修改名称啊)
executable_name: FlClash.exe
output_base_file_name: FlClash.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin